import { MediaType, ApplicationScenario } from '../entities/media.entity';

export const mediaSeedData = [
  {
    name: '单模光纤',
    type: MediaType.FIBER_OPTIC,
    maxDistance: 100,
    maxBandwidth: 100000,
    costPerKm: 8000,
    attenuation: 0.2,
    latency: 0.005,
    reliability: 9.5,
    installationDifficulty: 7,
    maintenanceCost: 800,
    environmentalAdaptability: 8,
    applicationScenarios: [ApplicationScenario.WAN, ApplicationScenario.LONG_HAUL, ApplicationScenario.METRO],
    specifications: 'ITU-T G.652标准，工作波长1310nm/1550nm',
    advantages: '传输距离远，带宽大，信号质量稳定，抗干扰能力强',
    disadvantages: '成本较高，安装复杂，需要专业设备和技术人员',
    isActive: true
  },
  {
    name: '多模光纤',
    type: MediaType.FIBER_OPTIC,
    maxDistance: 2,
    maxBandwidth: 10000,
    costPerKm: 3000,
    attenuation: 3.5,
    latency: 0.005,
    reliability: 9,
    installationDifficulty: 6,
    maintenanceCost: 300,
    environmentalAdaptability: 8,
    applicationScenarios: [ApplicationScenario.LAN, ApplicationScenario.DATACENTER, ApplicationScenario.CAMPUS],
    specifications: 'OM3/OM4标准，工作波长850nm/1300nm',
    advantages: '成本相对较低，安装相对简单，适合短距离高速传输',
    disadvantages: '传输距离有限，模式色散影响信号质量',
    isActive: true
  },
  {
    name: '六类双绞线',
    type: MediaType.COPPER,
    maxDistance: 0.1,
    maxBandwidth: 1000,
    costPerKm: 500,
    attenuation: 20,
    latency: 0.004,
    reliability: 7,
    installationDifficulty: 3,
    maintenanceCost: 50,
    environmentalAdaptability: 6,
    applicationScenarios: [ApplicationScenario.LAN, ApplicationScenario.CAMPUS],
    specifications: 'Cat6标准，支持千兆以太网',
    advantages: '成本低廉，安装简单，兼容性好，维护方便',
    disadvantages: '传输距离短，易受电磁干扰，带宽有限',
    isActive: true
  },
  {
    name: '超六类双绞线',
    type: MediaType.COPPER,
    maxDistance: 0.1,
    maxBandwidth: 10000,
    costPerKm: 800,
    attenuation: 15,
    latency: 0.004,
    reliability: 7.5,
    installationDifficulty: 4,
    maintenanceCost: 80,
    environmentalAdaptability: 6,
    applicationScenarios: [ApplicationScenario.LAN, ApplicationScenario.DATACENTER],
    specifications: 'Cat6A标准，支持万兆以太网',
    advantages: '支持更高带宽，向后兼容，成本适中',
    disadvantages: '传输距离仍然有限，对安装工艺要求较高',
    isActive: true
  },
  {
    name: '5G无线',
    type: MediaType.WIRELESS,
    maxDistance: 10,
    maxBandwidth: 20000,
    costPerKm: 15000,
    attenuation: 5,
    latency: 0.001,
    reliability: 8,
    installationDifficulty: 8,
    maintenanceCost: 2000,
    environmentalAdaptability: 7,
    applicationScenarios: [ApplicationScenario.CAMPUS, ApplicationScenario.METRO],
    specifications: '5G NR标准，工作频段3.5GHz/4.9GHz',
    advantages: '部署灵活，支持移动性，低延迟，高带宽',
    disadvantages: '覆盖范围有限，易受天气影响，功耗较高',
    isActive: true
  },
  {
    name: 'WiFi 6',
    type: MediaType.WIRELESS,
    maxDistance: 0.1,
    maxBandwidth: 9600,
    costPerKm: 5000,
    attenuation: 10,
    latency: 0.002,
    reliability: 6.5,
    installationDifficulty: 5,
    maintenanceCost: 500,
    environmentalAdaptability: 5,
    applicationScenarios: [ApplicationScenario.LAN, ApplicationScenario.CAMPUS],
    specifications: 'IEEE 802.11ax标准，2.4GHz/5GHz双频',
    advantages: '部署简单，成本较低，支持多设备并发',
    disadvantages: '覆盖范围小，易受干扰，安全性相对较低',
    isActive: true
  },
  {
    name: '卫星通信',
    type: MediaType.SATELLITE,
    maxDistance: 35000,
    maxBandwidth: 1000,
    costPerKm: 50000,
    attenuation: 0.1,
    latency: 0.25,
    reliability: 8.5,
    installationDifficulty: 9,
    maintenanceCost: 5000,
    environmentalAdaptability: 9,
    applicationScenarios: [ApplicationScenario.LONG_HAUL, ApplicationScenario.WAN],
    specifications: 'Ku/Ka频段，地球同步轨道卫星',
    advantages: '覆盖范围极广，不受地形限制，适合偏远地区',
    disadvantages: '延迟较高，成本昂贵，易受天气影响',
    isActive: true
  },
  {
    name: '同轴电缆',
    type: MediaType.COAXIAL,
    maxDistance: 1,
    maxBandwidth: 1000,
    costPerKm: 1000,
    attenuation: 8,
    latency: 0.004,
    reliability: 7.5,
    installationDifficulty: 4,
    maintenanceCost: 100,
    environmentalAdaptability: 7,
    applicationScenarios: [ApplicationScenario.LAN, ApplicationScenario.CAMPUS],
    specifications: 'RG-6/RG-11标准，75欧姆特性阻抗',
    advantages: '抗干扰能力强，传输稳定，成本适中',
    disadvantages: '带宽有限，安装相对复杂，体积较大',
    isActive: true
  }
];
